<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>Number Lock Puzzle</title>
<style>
  :root{
    --yellow:#F5C82D; --black:#111; --red:#D43D3D; --green:#2AA866;
  }
  body{font-family:system-ui,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:0;background:#fff;color:#111}
  header{display:flex;justify-content:flex-end;gap:12px;padding:14px}
  button{padding:.6rem .9rem;border:2px solid #222;border-radius:10px;background:#eee;font-weight:600;cursor:pointer}
  #check{background:#e9f6ea;border-color:#7dbc7d}
  #reset{background:#fdeaea;border-color:#f18a8a}
  .wrap{max-width:1024px;margin:0 auto;padding:10px 18px 40px}
  h1{font-size:24px;margin:6px 0 10px}
  .board{display:grid;grid-template-columns: 460px 1fr;gap:30px;align-items:start}
  /* lock panel */
  .lock{
    position:relative; padding:20px 16px 26px 16px; border:2px solid #222; border-radius:12px;
    min-height:280px;
    background:
      radial-gradient(120px 120px at 230px 24px, transparent 74px, #fff 75px) no-repeat;
  }
  .slots{display:flex;gap:14px;margin-top:160px;justify-content:center}
  .slot{
    width:70px;height:70px;border:3px solid #222;border-radius:10px;background:var(--yellow);
    display:flex;align-items:center;justify-content:center;font-size:40px;font-weight:800;user-select:none
  }
  .slot.active{outline:3px solid var(--green)}
  .msg{margin-top:16px;font-weight:700}
  /* hints */
  .hints{display:flex;flex-direction:column;gap:16px}
  .row{display:flex;align-items:center;gap:12px}
  .cells{display:flex;gap:10px}
  .cell{
    width:52px;height:52px;background:var(--yellow);border:2px solid #222;border-radius:8px;
    display:grid;place-items:center;font-size:28px;font-weight:800;cursor:pointer;position:relative;user-select:none
  }
  .cell.cross::before, .cell.cross::after{
    content:""; position:absolute; left:6px; right:6px; height:4px; background:var(--red);
    transform:rotate(45deg); top:24px; border-radius:2px
  }
  .cell.cross::after{ transform:rotate(-45deg) }
  .hinttext{font-size:14px;max-width:430px}
  .note{font-size:12px;opacity:.7;margin-top:6px}
  @media (max-width:900px){
    .board{grid-template-columns: 1fr}
  }
</style>
</head>
<body>
<header>
  <button id="check">Check</button>
  <button id="reset">Reset</button>
</header>

<div class="wrap">
  <h1>A number lock has a 3-digit code</h1>

  <div class="board">
    <!-- LOCK -->
    <div class="lock" id="lockArea" aria-label="Lock">
      <svg width="100%" height="150" style="position:absolute;left:0;top:10px;pointer-events:none">
        <!-- shackle -->
        <path d="M170,120 A120,120 0 0,1 370,120" fill="none" stroke="#111" stroke-width="10"/>
        <!-- body -->
        <rect x="60" y="140" width="420" height="120" rx="10" fill="#111"></rect>
        <rect x="74" y="154" width="392" height="92" rx="8" fill="#fff"></rect>
      </svg>

      <div class="slots" id="slots">
        <div class="slot" data-idx="0"></div>
        <div class="slot" data-idx="1"></div>
        <div class="slot" data-idx="2"></div>
      </div>
      <div class="msg" id="msg"></div>
      <div class="note">Tip: klik kotak gembok lalu ketik angka 0–9. Klik angka petunjuk untuk mencoret.</div>
    </div>

    <!-- HINTS -->
    <div class="hints" id="hints"></div>
  </div>
</div>

<script>
  // ====== Konfigurasi ======
  const SOLUTION = [0,5,2]; // ubah kalau mau variasi

  const hintData = [
    {digits:[6,8,2], text:"one number is correct and in the correct position"},
    {digits:[6,4,5], text:"one number is correct but in the wrong position"},
    {digits:[2,0,6], text:"two numbers are correct but in the wrong positions"},
    {digits:[7,3,8], text:"nothing is correct"},
    {digits:[7,8,0], text:"one number is correct but in the wrong position"}
  ];

  // ====== Render hints ======
  const hintsEl = document.getElementById('hints');
  hintData.forEach((row, rIdx)=>{
    const rowEl = document.createElement('div');
    rowEl.className = 'row';

    const cells = document.createElement('div');
    cells.className = 'cells';

    row.digits.forEach((d,cIdx)=>{
      const cell = document.createElement('div');
      cell.className = 'cell';
      cell.textContent = d;
      cell.addEventListener('click', ()=> cell.classList.toggle('cross'));
      cells.appendChild(cell);
    });

    const text = document.createElement('div');
    text.className = 'hinttext';
    text.textContent = row.text;

    rowEl.appendChild(cells);
    rowEl.appendChild(text);
    hintsEl.appendChild(rowEl);
  });

  // ====== Lock input ======
  const slots = [...document.querySelectorAll('.slot')];
  const msg = document.getElementById('msg');
  let active = -1;
  const code = ["","",""];

  function setActive(i){
    active = i;
    slots.forEach((s,idx)=> s.classList.toggle('active', idx===i));
  }
  slots.forEach(s=>{
    s.addEventListener('click', ()=> setActive(parseInt(s.dataset.idx,10)));
  });

  document.addEventListener('keydown', (e)=>{
    if(active<0) return;
    if(/[0-9]/.test(e.key)){
      code[active] = e.key;
      slots[active].textContent = e.key;
    }else if(e.key==='Backspace'){
      code[active] = "";
      slots[active].textContent = "";
    }else if(e.key==='ArrowLeft'){
      setActive(Math.max(0, active-1));
    }else if(e.key==='ArrowRight'){
      setActive(Math.min(2, active+1));
    }
  });

  // ====== Buttons ======
  document.getElementById('check').addEventListener('click', ()=>{
    if(code.some(v=>v==="")){
      msg.style.color = '#D43D3D';
      msg.textContent = 'Isi dulu ketiga angka!';
      return;
    }
    const guess = code.map(x=>parseInt(x,10));
    const ok = guess.every((v,i)=> v===SOLUTION[i]);
    msg.style.color = ok ? '#2AA866' : '#D43D3D';
    msg.textContent = ok ? `Benar! Kodenya ${guess.join('')}.` : 'Belum benar. Coba lagi!';
  });

  document.getElementById('reset').addEventListener('click', ()=>{
    // clear strike and inputs
    document.querySelectorAll('.cell.cross').forEach(el=> el.classList.remove('cross'));
    code.fill("");
    slots.forEach(s=> s.textContent = "");
    setActive(-1);
    msg.textContent = "";
  });
</script>
</body>
</html>
